language: php

php:
  - '7.0'
  - '7.1'

install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls
